import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils"; // Assuming utils are generated by shadcn/ui

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Olie ERP - Protótipo",
  description: "Protótipo navegável do sistema ERP Olie",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}>
        <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 items-center">
            <div className="mr-4 hidden md:flex">
              <Link href="/" className="mr-6 flex items-center space-x-2">
                {/* Add logo here if available */}
                <span className="hidden font-bold sm:inline-block">
                  Olie ERP - Protótipo
                </span>
              </Link>
              <nav className="flex items-center space-x-6 text-sm font-medium">
                <Link
                  href="/"
                  className="transition-colors hover:text-foreground/80 text-foreground/60"
                >
                  Início
                </Link>
                <Link
                  href="/produtos"
                  className="transition-colors hover:text-foreground/80 text-foreground/60"
                >
                  Produtos
                </Link>
                <Link
                  href="/pedidos"
                  className="transition-colors hover:text-foreground/80 text-foreground/60"
                >
                  Pedidos
                </Link>
                <Link
                  href="/producao"
                  className="transition-colors hover:text-foreground/80 text-foreground/60"
                >
                  Produção
                </Link>
                {/* Add Estoque link later if needed */}
              </nav>
            </div>
            {/* Add mobile menu button here if needed */}
          </div>
        </header>
        <main className="container py-6">
          {children}
        </main>
        <footer className="py-6 md:px-8 md:py-0">
            <div className="container flex flex-col items-center justify-center gap-4 md:h-24 md:flex-row">
                <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
                    © {new Date().getFullYear()} Olie Ateliê - Protótipo ERP
                </p>
            </div>
        </footer>
      </body>
    </html>
  );
}

